config/routes.rb
Rails.application.routes.draw do
  get "minions/busca", to: "minions#busca", as: :busca_minion
  root to: "minions#index"
    resources :minions, only: [:new, :create, :destroy, :edit, :update] do
      member do
        get 'envio_email'
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minion.rb
class Minion < ApplicationRecord
    validates :preco, presence: true
    validates :nome, length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minions_controller.rb
class MinionsController < ApplicationController

    before_action :set_minion, only: [:edit, :update, :destroy]

    def index
        @minions = Minion.order(nome: :asc)
        @minion_com_desconto = Minion.order(:preco).limit 2
    end

    def new
        @minion = Minion.new
    end

    def edit
        renderiza :edit
    end

    def update
        if @minion.update minion_params
          flash[:notice] = "Minion atualizado com sucesso!"
          redirect_to root_url
       else    
         renderiza :edit
       end

    end

    def create
        @minion = Minion.new minion_params
        if @minion.save
            flash[:notice] = "Minion cadastrado com sucesso!"
            redirect_to root_url
        else
            renderiza :new
        end
    end

    def destroy
        @minion.destroy
        flash[:notice] = "Minion removido com sucesso!"
        redirect_to root_url
    end

    def envio_email
        @minion = Minion.find(params[:id])
        EmailReservaMailer.email_reserva(@minion).deliver
        flash[:notice] = "Minion reservado com sucesso! Favor checar sua caixa de entrada de e-mail"
        redirect_to root_url
    end

    def busca
        @nome = params[:nome]
        @minions = Minion.where("lower(nome) like ?", "%#{@nome.downcase}%")
    end

    private

    def minion_params 
        params.require(:minion).permit(:nome, :descricao, :preco, :quantidade)
    end

    def set_minion
        @minion = Minion.find(params[:id])
    end

    def renderiza(view)
        render view
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minions_helper.rb
module MinionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioInventos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= nav_bar brand: "Loja", brand_link: root_url do %>
    <%= menu_group do %>
      <%= menu_item "Cadastrar novo minion", new_minion_path %>
      <% end %>
      <%= form_tag busca_minion_path, method: :get, 
      class:"navbar-form navbar-right" do %>
      <div class="form-group">
          <%= text_field_tag :nome, @nome, class:"form-control" %>
          <%= button_to "Buscar", nil, class:"btn btn-default" %>
       </div>
      <% end %>
    <% end %>
  <div class="container"> 
    <%= yield %>
  </div>
  </body>
</html>

app/views/minions/_form.html.erb
<% @minion.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
        <%= msg %>
        </div>
 <% end %>

<%= form_for @minion do |form| %>
    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <%= form.label :nome %> 
                <%= form.text_field :nome, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <%= form.label :descricao %>
                <%= form.text_area :descricao, class:"form-control", rows:"4" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :preco %>
                <%= form.number_field :preco, step:0.01, class:"form-control" %>
            </div>
        </div>
    </div>   

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
            <%= form.label :quantidade %>
            <%= form.number_field :quantidade, class:"form-control" %>
        </div>
    </div>
</div>
    <%= form.submit texto_da_acao, class:"btn btn-primary" %>
<% end %>                       

app/views/minions/_minion.html.erb
 <tr>
    <td><%= minion.nome %></td>
    <td><%= minion.descricao %></td>
    <td><%= minion.preco %></td>
    <td><%= minion.quantidade %></td>
    <td><%= link_to "Alterar", edit_minion_path(minion), class:"btn btn-default" %>
    <td><%= button_to "Remover", minion, method: :delete,
    class:"btn btn-danger btn-sm",
    data: {confirm: "Tem certeza que deseja remover o #{minion.nome}?"} %>
    <td><%= link_to "Reservar", envio_email_minion_path(minion), class:"btn btn-primary" %></td>
 </tr>           

app/views/minions/busca.html.erb
<table class="table table-bordered table-hover">
    <thrad>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan="2">
         </tr>
    </thrad>   
    <tbody>
        <%= render @minions %>
    </tbody>    
</table>

app/views/minions/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Atualizar"} %>

app/views/minions/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div> 
<% end %>

<table class="table table-bordered table-hover">
    <thrad>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan="2">
        </tr>
    </thrad> 
    <tbody>
         <%= render @minions %>
    </tbody>    
</table>
<div class="alert alert-success" role="alert">
<h4 class="alert-heading">Minions com desconto</h4>
</div>
<table class="table table-bordered table-hover">
    <thrad>
        <tr>
        <td>Nome</td>
        <td>Descrição</td>
        <td>Preço</td>
        <td>Quantidade</td>
        <td colspan="2">
        </tr>
    </thrad>   
    <tbody>
        <%= render @minion_com_desconto %>
    </tbody>    
</table>

app/views/minions/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Cadastrar"} %>